FROM golang:1.19-alpine AS builder

RUN apk add --no-cache git

WORKDIR /app

COPY go.* ./
RUN go mod download

COPY . .
RUN go build -o /app/server

FROM alpine:latest

RUN apk add --no-cache ca-certificates

COPY --from=builder /app/server /server

EXPOSE 8080

CMD ["/server"]
